### ISSUE TITLE
Your demo is broken

### ISSUE THREAD

**Issue by yossely** [SidebarJS/ng-sidebarjs#1]
Your dome is broken... Take a look

https://www.webpackbin.com/bins/-KowIAML_Tti73FWyyzp

![image](https://user-images.githubusercontent.com/5514988/32862834-6adf0f3a-ca27-11e7-9b08-804462b11336.png)

**Comment by lorenzodianni** [comment]
Thanks @yossely, unfortunately WebpackBin introduced a bug for Angular projects, there is an [open issue](https://github.com/cerebral/webpackbin/issues/48) for that.

Do you know a WebpackBin alternative?

**Comment by yossely** [comment]
Uh no sorry, I don't know any
