### ISSUE TITLE
Swiping seems unreliable

### ISSUE THREAD

**Issue by pulsejet** [SidebarJS/ng-sidebarjs#3]
First of all, very nice project you're doing here =D
However, swiping on mobile seems a bit unreliable, where it sometimes happens and sometimes doesn't. Is this a known bug?

EDIT: This happens only when swiping right from the edge. It works almost always when swiping from a few pixels inside.

**Comment by lorenzodianni** [comment]
Hi @pulsejet, thanks!
Please, can you tell me on which device and OS did you find this bug?

**Comment by pulsejet** [comment]
Hi! It is reproducible on my Xperia M5 with updated Chrome and Marshmallow.

**Comment by pulsejet** [comment]
Also, I have an angular application with a whole bunch of animations. When I add this to it, it works fine initially, but sometimes just opens when I scroll up after navigating to another component (Router). Can't really figure out why this could be happening.

**Comment by lorenzodianni** [comment]
Can you make a [stackblitz](https://stackblitz.com/) example please?
Do you have some EventEmitter on change route?
