### ISSUE TITLE
Sidebar automatically appear in Mobile view...??

### ISSUE THREAD

**Issue by paragyelonde** [SidebarJS/ng-sidebarjs#5]
Hey,
Sidebar is working properly in Desktop view but when i check it on my mobile then sidebar automatically appear on my screen on scroll..??

`<sidebar-js sidebarjsConfig="{documentSwipeRange?: 40, documentMinSwipeX?: 10,}">
            <ul class="navbar-nav mr-0 custom_navbar_margin1">
                  <li class="nav-item">
                    <a class="nav-link mobile_nav_link" routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{exact:true}" sidebarjsClose>Home <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link mobile_nav_link" routerLink="/about" routerLinkActive="active" sidebarjsClose>About</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Products
                    </a>
                    <div class="dropdown-menu ml-2" aria-labelledby="navbarDropdown" style="width: 3rem;">
                      <a class="dropdown-item mobile_nav_link" routerLink="/" sidebarjsClose>Lipstick</a>
                      <a class="dropdown-item mobile_nav_link" routerLink="/" sidebarjsClose>Maskara</a>
                      <a class="dropdown-item mobile_nav_link" routerLink="/" sidebarjsClose>Foundation</a>
                      <a class="dropdown-item mobile_nav_link" routerLink="/" sidebarjsClose>Eyeliner</a>
                      
                    </div>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Brands
                    </a>
                    <div class="dropdown-menu ml-2" aria-labelledby="navbarDropdown" style="width: 3rem;">
                      <a class="dropdown-item mobile_nav_link" routerLink="/" sidebarjsClose>Brand1</a>
                      <a class="dropdown-item mobile_nav_link" routerLink="/" sidebarjsClose>Brand2</a>
                      <a class="dropdown-item mobile_nav_link" routerLink="/" sidebarjsClose>Brand3</a>
                      <a class="dropdown-item mobile_nav_link" routerLink="/" sidebarjsClose>Brand4</a>
                      
                    </div>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link mobile_nav_link" routerLink="/contact" routerLinkActive="active" sidebarjsClose>Contact</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link mobile_nav_link" routerLink="/logout" routerLinkActive="active" sidebarjsClose>Log Out</a>
                  </li>
                </ul>
              </sidebar-js>`

**Comment by lorenzodianni** [comment]
Please provide an example on https://stackblitz.com/

**Comment by paragyelonde** [comment]
https://stackblitz.com/edit/angular-5gdltt?file=app%2Fapp.component.html


link of my code but i didnot get how to apply on there.
