### ISSUE TITLE
not working in angular 11

### ISSUE THREAD

**Issue by Digoro** [SidebarJS/ng-sidebarjs#8]
I installed angular 11 and ng-sidebarjs 4 and 6 versions, but it doesn't work.
An undefined error occurs because the component and container nativeElement do not exist.

![image](https://user-images.githubusercontent.com/6007757/209611206-4d7bff37-f707-4cf0-a6e4-c7764eac8da0.png)

**Comment by lorenzodianni** [comment]
Hi @Digoro, please can you provide a [stackblitz](https://stackblitz.com/) example?

**Comment by Digoro** [comment]
Example is here.
https://stackblitz.com/edit/ng-sidebarjs-zeqrqg (angular version: 11, ng-sidebarjs: 4)
and i try other version(angular version 11, ng-sidebarjs: 6), also not working, same error.

**Comment by lorenzodianni** [comment]
Thanks! Fixed end released a specific version for angular 11 🚀 
Try to  install [ng-sidebarjs@11](https://www.npmjs.com/package/ng-sidebarjs/v/11.0.2), there is a working example: https://stackblitz.com/edit/ng-sidebarjs-11

Remember to follow the [migration guide](https://github.com/SidebarJS/ng-sidebarjs#migrate-from-400-to-600) and if something doesn't work as expected, feel free to reopen the issue 😉
